# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instagram_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instagram_ios
  pod 'Alamofire'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Then'
  pod "BSImagePicker", "~> 3.1"
  pod 'Tabman', '~> 3.0'
  pod 'YPImagePicker'
end
